# ── Encryption key ────────────────────────────────────────────────────────────
# Generated by default. var.n8n_encryption_key overrides it: see the variable
# description for why: restoring an RDS snapshot into a new stack otherwise
# re-generates a key that cannot decrypt the credentials the restored database
# already holds.

resource "random_id" "n8n_encryption_key" {
  count = var.n8n_encryption_key == null && var.n8n_encryption_key_secret_ref == null ? 1 : 0

  byte_length = 32
}

locals {
  # null when n8n_encryption_key_secret_ref is set: there is no module-known
  # key value in that case, since the module never reads the caller's Secret
  # (see that variable's description for why). secretRefs.existingSecret
  # points the chart at the caller's own Secret name instead, below.
  n8n_encryption_key = var.n8n_encryption_key_secret_ref != null ? null : coalesce(var.n8n_encryption_key, try(random_id.n8n_encryption_key[0].hex, null))
}

# There is deliberately no check block warning about n8n_encryption_key, even
# though setting it wrongly is the most destructive single input mistake this
# module allows: a value that does not match the key the target database's
# credentials were encrypted under makes every one of them permanently
# unreadable, with no recovery path on n8n's side.
#
# Nothing checkable at plan time separates the safe uses from the unsafe one.
# The distinguishing fact is what the live database already holds, which no
# Terraform expression can read. An earlier version of this module warned
# whenever the input was combined with create_database = false, and that turned
# out to be precisely backwards:
#
#   - It fired on the intended use. aws_db_instance.n8n takes no
#     snapshot_identifier, so restoring a database into a rebuilt stack (the
#     case the variable and the n8n_encryption_key output both document as the
#     reason this input exists) means restoring outside the module and pointing
#     at it with create_database = false. The warning landed on the documented
#     happy path.
#   - It stayed silent on the likeliest mistake: editing this value in tfvars on
#     a live create_database = true deployment that already holds credentials
#     under the generated key. That plans clean, applies clean, and destroys
#     every credential.
#
# A warning that fires on correct usage and passes the real error trains people
# to ignore it, so the guidance lives where it can be read before the apply
# instead: the variable description in variables.tf, the n8n_encryption_key
# output description, and README.md.

# ── Task runner auth token ─────────────────────────────────────────────────────
# Generated once and stored in state. Used as the shared secret between the n8n
# task broker (port 5679) and the runner sidecars on main and worker pods.
# Only active when n8n_task_runners_enabled = true.

resource "random_password" "task_runner_token" {
  length  = 32
  special = false
}

locals {
  # Per-credential key defaults when a *_secret_ref input's optional `key` is
  # omitted, resolved once here rather than in each variable's type
  # constraint (an omitted optional() attribute is null, not a useful
  # default), so the fallback is visible and testable in one place. null when
  # the corresponding *_secret_ref input itself is null; every reference below
  # guards on that separately.
  n8n_license_key_secret_ref_key  = var.n8n_license_key_secret_ref == null ? null : coalesce(var.n8n_license_key_secret_ref.key, "license-key")
  db_password_secret_ref_key      = var.db_password_secret_ref == null ? null : coalesce(var.db_password_secret_ref.key, "password")
  redis_auth_token_secret_ref_key = var.redis_auth_token_secret_ref == null ? null : coalesce(var.redis_auth_token_secret_ref.key, "password")
}

# ── Namespace ─────────────────────────────────────────────────────────────────
# Skipped when create_namespace = false: the caller deploys into a namespace
# that already exists. local.namespace_name below resolves to this resource's
# name when the module creates it, or to var.namespace directly otherwise;
# every other reference to the namespace name goes through that local, not
# through this resource, so it works on either path.

resource "kubernetes_namespace" "n8n" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name = var.namespace
  }

  timeouts {
    delete = "2m"
  }

  depends_on = [aws_eks_node_group.n8n]
}

locals {
  namespace_name = var.create_namespace ? kubernetes_namespace.n8n[0].metadata[0].name : var.namespace
}

# ── Secrets ───────────────────────────────────────────────────────────────────
# Multi-main needs two secrets: one for core n8n config, one for the DB password.
#
# N8N_LICENSE_ACTIVATION_KEY reaches the chart through a Secret reference
# rather than being passed as a literal value. The chart accepts it either
# way, and the literal form writes it into the rendered Helm release values,
# which Helm then stores in its own release Secret in the cluster
# (sha256-addressed, retained per revision) on top of Terraform state. A
# Secret reference keeps it in exactly one place. Every other credential the
# module handles already works this way: the DB password, the Redis AUTH
# token and the encryption key. The task runner auth token is the exception:
# it encrypts nothing, so it is passed to the chart as a literal value like
# it always has been.
#
# This does not remove the license key from Terraform state: it is a module
# input either way, so it stays in state regardless; what changes is that it
# stops being copied into the Helm release as well.

resource "kubernetes_secret" "n8n" {
  # Gated to zero only when n8n_encryption_key_secret_ref replaces this Secret
  # entirely: the chart's secretRefs.existingSecret names one Secret for all
  # four of N8N_ENCRYPTION_KEY, N8N_HOST, N8N_PORT and N8N_PROTOCOL, so there
  # is no way to keep this Secret around for the other three and still point
  # the encryption key at a caller-supplied one. See that variable's
  # description for the coupling this implies for the license key.
  #
  # The license key is handled differently: it is dropped from `data` (not
  # gated onto this resource's count) when n8n_license_key_secret_ref is set,
  # since kubernetes_secret.n8n keeps existing for the other configuration
  # keys either way on that path. See the `merge()` below.
  count = var.n8n_encryption_key_secret_ref == null ? 1 : 0

  metadata {
    name      = "n8n-enterprise-secrets"
    namespace = local.namespace_name
  }

  data = merge(
    {
      N8N_ENCRYPTION_KEY = local.n8n_encryption_key
      N8N_HOST           = local.n8n_domain
      N8N_PORT           = "5678"
      N8N_PROTOCOL       = "http"
      WEBHOOK_URL        = coalesce(var.n8n_webhook_url, "https://${local.n8n_domain}")
    },
    # Dropped rather than merged in as null when the caller's own Secret
    # carries the license key instead: license.existingSecret then points
    # straight at var.n8n_license_key_secret_ref.name below, and this key
    # would otherwise sit in kubernetes_secret.n8n unread.
    var.n8n_license_key_secret_ref == null ? { N8N_LICENSE_ACTIVATION_KEY = var.n8n_license_key } : {},
  )

  # local.namespace_name only carries an implicit dependency on
  # kubernetes_namespace.n8n when create_namespace = true. On the
  # create_namespace = false path that resource has zero instances, so without
  # this the secret would have no ordering relative to the node group at all.
  depends_on = [aws_eks_node_group.n8n]
}

resource "kubernetes_secret" "n8n_db" {
  # Gated to zero when db_password_secret_ref points the chart at a Secret the
  # caller already manages instead. Single-purpose Secret, unlike
  # kubernetes_secret.n8n above, so the whole resource is skipped rather than
  # one key dropped from it. Only reachable with create_database = false: see
  # db_password_secret_ref's validation.
  count = var.db_password_secret_ref == null ? 1 : 0

  metadata {
    name      = "n8n-enterprise-db-secret"
    namespace = local.namespace_name
  }

  data = {
    # Use caller-supplied password when an external DB is provided, otherwise use the generated one.
    password = var.create_database ? random_password.db_password.result : var.db_password
  }

  # See the comment on kubernetes_secret.n8n above.
  depends_on = [aws_eks_node_group.n8n]
}

# ── Redis AUTH secret ─────────────────────────────────────────────────────────
# The Redis AUTH token, on the same shape as the DB secret above. The chart
# mounts it as QUEUE_BULL_REDIS_PASSWORD on main, worker and webhook processor
# via redis.passwordSecret (see the Helm values below). Exists only on the
# opt-in path: there is no token to hold otherwise. local.redis_auth_token_value
# resolves to the module-generated token (create_elasticache = true) or the
# caller-supplied var.redis_auth_token (create_elasticache = false), see
# locals.tf.

resource "kubernetes_secret" "n8n_redis" {
  # Also gated on redis_auth_token_secret_ref: a caller-managed Secret needs no
  # module-managed twin. This resource was already indexed before that
  # addition (count already gated on local.redis_auth_active alone), so
  # narrowing the condition further does not move its address the way gating
  # kubernetes_secret.n8n and kubernetes_secret.n8n_db above does for the
  # first time; no `moved` block is needed here. See refactoring.tf.
  count = local.redis_auth_active && var.redis_auth_token_secret_ref == null ? 1 : 0

  metadata {
    name      = "n8n-enterprise-redis-secret"
    namespace = local.namespace_name
  }

  data = {
    password = local.redis_auth_token_value
  }

  # See the comment on kubernetes_secret.n8n above.
  depends_on = [aws_eks_node_group.n8n]
}

# ── Service account ───────────────────────────────────────────────────────────
# Only created when var.n8n_image_pull_secrets is non-empty. Otherwise the chart
# creates the account and this resource does not exist; see the note on
# local.n8n_manages_service_account for why the module ever takes it over.
#
# The name is deliberately not the one the chart uses, so that enabling the
# input on a live deployment does not collide with the account Helm already
# owns; locals.tf has the full reasoning. The Pod Identity association in s3.tf
# reads the same local, so it follows the account whichever name is in play.
#
# The chart's eks.amazonaws.com/role-arn annotation is not reproduced here on
# purpose: the module authenticates through Pod Identity, not IRSA, and the
# annotation was only ever passed to satisfy the chart's own template
# validation, which reads serviceAccount.awsRoleArn from the values regardless
# of who creates the account.
#
# automount_service_account_token is set explicitly because the provider
# defaults it to false, which would be a behaviour change: the chart leaves the
# field unset, and an unset ServiceAccount field means the pod mounts the token.

resource "kubernetes_service_account_v1" "n8n" {
  count = local.n8n_manages_service_account ? 1 : 0

  metadata {
    name      = local.n8n_service_account_name
    namespace = local.namespace_name
  }

  automount_service_account_token = true

  dynamic "image_pull_secret" {
    for_each = var.n8n_image_pull_secrets
    content {
      name = image_pull_secret.value
    }
  }

  # See the comment on kubernetes_secret.n8n above.
  depends_on = [aws_eks_node_group.n8n]
}

# ── Helm release ──────────────────────────────────────────────────────────────

resource "helm_release" "n8n" {
  name            = "n8n"
  repository      = var.n8n_chart_repository
  chart           = "n8n"
  version         = var.n8n_chart_version
  namespace       = local.namespace_name
  wait            = true
  timeout         = var.n8n_helm_timeout
  atomic          = true
  cleanup_on_fail = true

  values = [yamlencode(merge({
    # activationKey is deliberately absent: the chart's licenseEnv helper is
    # `if .Values.license.activationKey / else if .Values.license.existingSecret.name`,
    # so sending both would silently keep the inline path and change nothing.
    # existingSecret takes the nested {name, key} shape here, unlike
    # taskRunners.authToken below, which takes two flat keys.
    #
    # Only main and worker pods receive the license env var: at the pinned chart
    # version deployment-webhook-processor.yaml does not include licenseEnv at
    # all. That is unchanged by this wiring, since the inline form was rendered
    # through the same helper.
    # name/key fall back to kubernetes_secret.n8n when n8n_license_key_secret_ref
    # is null (the default, no change from before this input existed), and
    # point at the caller's own Secret otherwise. See that variable and
    # n8n_encryption_key_secret_ref for when kubernetes_secret.n8n itself does
    # not exist, in which case n8n_license_key_secret_ref is required.
    license = {
      enabled = true
      existingSecret = {
        name = var.n8n_license_key_secret_ref != null ? var.n8n_license_key_secret_ref.name : kubernetes_secret.n8n[0].metadata[0].name
        key  = var.n8n_license_key_secret_ref != null ? local.n8n_license_key_secret_ref_key : "N8N_LICENSE_ACTIVATION_KEY"
      }
    }

    # ── Deployment replica counts ─────────────────────────────────────────────
    # Each of the three below is wired to its autoscaler's floor rather than left
    # at a constant, because the chart renders spec.replicas unconditionally:
    # deployment-main.yaml uses multiMain.replicas, deployment-worker.yaml uses
    # queueMode.workerReplicaCount, and deployment-webhook-processor.yaml uses
    # webhookProcessor.replicaCount, with no regard for whether an HPA or a KEDA
    # ScaledObject also owns the field.
    #
    # A constant here fights the autoscaler on every helm upgrade. Helm writes
    # spec.replicas back to the constant, the deployment scales down to it, and
    # the autoscaler then has to scale back up to its floor, which erases the warm
    # floor at exactly the moment a rollout needs it. Setting each to its floor
    # makes Helm's write a no-op while the deployment sits at that floor.
    #
    # It does not preserve an active scale-up. A deployment the autoscaler has
    # taken above its floor is still written down to the floor on the next
    # upgrade, and the autoscaler has to climb again. Bounding the drop at the
    # floor is the most a caller of this chart can do: the field is rendered
    # unconditionally, so no value omits it, and reading the live replica count
    # back into the plan would make every plan depend on current cluster state.
    # Fixing it properly means the chart guarding spec.replicas on whether an
    # autoscaler owns the deployment.

    multiMain = {
      enabled  = true
      replicas = var.n8n_main_hpa_min_replicas
      antiAffinity = {
        type = "preferred"
      }
    }

    queueMode = {
      enabled            = true
      workerReplicaCount = var.n8n_worker_keda_min_replicas
      workerConcurrency  = var.n8n_worker_concurrency
    }

    webhookProcessor = {
      enabled                                = true
      replicaCount                           = var.n8n_webhook_hpa_min_replicas
      disableProductionWebhooksOnMainProcess = true
    }

    database = {
      type        = "postgresdb"
      useExternal = true
      # Module-managed RDS when create_database = true, otherwise the caller-supplied
      # db_host (which may point at an external DB or an in-cluster connection pooler).
      host = var.create_database ? aws_db_instance.n8n[0].address : var.db_host
      port = 5432
      # Hardcoded on both the create_database = true and = false paths: there
      # is no db_name variable. On create_database = false this means
      # db_host is shared down to the exact database and tables, not merely
      # the RDS instance/host -- confirmed live, see db_host's description.
      # This supports "point a new stack at the same RDS instance a previous
      # stack used" (a migration/cutover pattern: stop the old writer first,
      # then cut over) but not true concurrent multi-tenant sharing of one
      # RDS instance across logically separate n8n deployments, which would
      # need a caller-chosen database name on both paths and does not exist
      # today.
      database = "n8n_enterprise"
      schema   = "public"
      user     = "n8n"
      # name/key fall back to kubernetes_secret.n8n_db when db_password_secret_ref
      # is null (the default), and point at the caller's own Secret otherwise;
      # see that variable.
      passwordSecret = {
        name = var.db_password_secret_ref != null ? var.db_password_secret_ref.name : kubernetes_secret.n8n_db[0].metadata[0].name
        key  = var.db_password_secret_ref != null ? local.db_password_secret_ref_key : "password"
      }
    }

    # passwordSecret is merged in rather than set inline so the default path
    # renders exactly the five keys it always has. The chart's default for it is
    # null and its templates guard on `if and .name .key`, so an omitted key and
    # an explicit null behave the same, but omitting it keeps the rendered
    # values byte-identical for existing releases, which is what makes the
    # upgrade a no-op rather than a Helm diff.
    redis = merge({
      enabled     = true
      useExternal = true
      # local.redis_host / local.redis_port resolve the module-managed single
      # node, the module-managed replication group's primary endpoint, or the
      # caller's own Redis. See redis.tf.
      host = local.redis_host
      port = local.redis_port
      tls  = local.redis_tls_active
      },
      local.redis_timeout_values,
      # Same omit-when-unset treatment as passwordSecret, and for the same
      # reason: the chart guards on `if .Values.redis.username`, so an explicit
      # null and an omitted key behave identically, but omitting it keeps the
      # rendered values byte-identical for every release that does not set it.
      local.redis_username_value != null ? { username = local.redis_username_value } : {},
      # name/key fall back to kubernetes_secret.n8n_redis when
      # redis_auth_token_secret_ref is null (the default), and point at the
      # caller's own Secret otherwise; see that variable.
      local.redis_auth_active ? {
        passwordSecret = {
          name = var.redis_auth_token_secret_ref != null ? var.redis_auth_token_secret_ref.name : kubernetes_secret.n8n_redis[0].metadata[0].name
          key  = var.redis_auth_token_secret_ref != null ? local.redis_auth_token_secret_ref_key : "password"
        }
      } : {},
      # Sets QUEUE_BULL_PREFIX (configmap.yaml's `if .Values.redis.prefix`
      # guard omits it entirely when unset, so n8n's own "bull" default
      # applies exactly as before on the null path). The matching
      # N8N_REDIS_KEY_PREFIX env var lives in config.extraEnv below, and the
      # KEDA listName values a few blocks down are kept in sync with this same
      # variable: all three have to move together, see redis_key_prefix.
      var.redis_key_prefix != null ? { prefix = var.redis_key_prefix } : {},
      # QUEUE_WORKER_LOCK_DURATION, QUEUE_WORKER_LOCK_RENEW_TIME and
      # QUEUE_WORKER_STALLED_INTERVAL are chart-templated from redis.worker.*
      # (values.yaml), and are NOT names config.extraEnv can safely set: the
      # chart's own ConfigMap entries for these keys render unconditionally,
      # so an extraEnv duplicate produces a container env entry with both
      # `value` and a `valueFrom.configMapKeyRef` set, which the Kubernetes
      # API rejects outright ("may not be specified when value is not
      # empty"). The whole `worker` key is omitted when none of the three is
      # set, leaving the chart's own defaults (60000 / 10000 / 30000 ms).
      #
      # local.n8n_queue_worker_settings, not the variables directly: this
      # merge is shallow, so three separate `worker` entries would overwrite
      # each other and only the last would survive. See locals.tf.
      length(local.n8n_queue_worker_settings) > 0 ? {
        worker = local.n8n_queue_worker_settings
      } : {}
    )

    s3 = {
      enabled = true
      bucket = {
        name   = local.s3_bucket_name
        region = local.aws_region
      }
      auth = { autoDetect = true }
      storage = {
        mode           = "s3"
        availableModes = "filesystem,s3"
      }
    }

    # S3 credentials are injected by EKS Pod Identity (s3.tf).
    # awsRoleArn is provided only to satisfy the chart's template validation —
    # the actual auth comes from the Pod Identity agent, not IRSA. The chart
    # requires it whenever s3.auth.autoDetect is true, independently of who
    # creates the account, so it stays set on both branches of `create`.
    serviceAccount = {
      create     = !local.n8n_manages_service_account
      name       = local.n8n_service_account_name
      awsRoleArn = aws_iam_role.s3.arn
    }

    # Bare Secret name, unlike the other four *_secret_ref inputs' nested or
    # flat {name, key} shapes: coreSecretsEnv hardcodes the key it reads for
    # each of the four values this Secret carries. See
    # n8n_encryption_key_secret_ref's description for the four-key contract a
    # caller-supplied Secret has to satisfy.
    secretRefs = {
      existingSecret = var.n8n_encryption_key_secret_ref != null ? var.n8n_encryption_key_secret_ref.name : kubernetes_secret.n8n[0].metadata[0].name
    }

    service = {
      type = "ClusterIP"
      port = 5678
    }

    hpa = {
      main = {
        enabled                        = true
        minReplicas                    = var.n8n_main_hpa_min_replicas
        maxReplicas                    = var.n8n_main_hpa_max_replicas
        targetCPUUtilizationPercentage = var.n8n_main_hpa_cpu_threshold
      }
      webhookProcessor = {
        enabled                        = true
        minReplicas                    = var.n8n_webhook_hpa_min_replicas
        maxReplicas                    = var.n8n_webhook_hpa_max_replicas
        targetCPUUtilizationPercentage = var.n8n_webhook_hpa_cpu_threshold
      }
    }

    # ── KEDA: queue-depth autoscaling for workers ─────────────────────────────
    # Scales workers based on Redis queue depth rather than CPU — workers appear
    # only when there are jobs and scale in proportion to backlog.
    # Two triggers: bull:jobs:wait (queued jobs) + bull:jobs:active (jobs held by
    # workers waiting for a task runner). KEDA takes the MAX of both.
    # Webhook processor HPA is created externally in scaling.tf (chart skips it
    # when keda.enabled = true).
    #
    # When redis_transit_encryption_enabled = true both triggers additionally
    # carry TLS and an AUTH token, merged in from local.keda_redis_auth_metadata
    # (see locals.tf for how the token reaches KEDA without being written into
    # the ScaledObject). Both keys are needed and TLS is the one that has to
    # land: without it KEDA opens a plaintext connection to a TLS-only endpoint
    # and hangs on `connection to redis failed: i/o timeout` before it ever
    # reaches authentication. The HPA then reports `<unknown>` and workers
    # freeze at their current replica count, which nothing crashes to announce.
    keda = {
      enabled = true
      worker = {
        pollingInterval = 15
        cooldownPeriod  = 60
        minReplicaCount = var.n8n_worker_keda_min_replicas
        maxReplicaCount = var.n8n_worker_keda_max_replicas
        triggers = [
          {
            type = "redis"
            metadata = merge({
              address    = "${local.redis_host}:${local.redis_port}"
              listName   = "${local.redis_key_prefix_value}:jobs:wait"
              listLength = tostring(var.n8n_worker_keda_jobs_per_replica)
            }, local.keda_redis_auth_metadata)
            authenticationRef = { name = "" }
          },
          {
            type = "redis"
            metadata = merge({
              address    = "${local.redis_host}:${local.redis_port}"
              listName   = "${local.redis_key_prefix_value}:jobs:active"
              listLength = tostring(var.n8n_worker_keda_jobs_per_replica)
            }, local.keda_redis_auth_metadata)
            authenticationRef = { name = "" }
          }
        ]
      }
    }

    resources = {
      main = {
        requests = { cpu = var.n8n_main_cpu_request, memory = var.n8n_main_memory_request }
        limits   = { cpu = var.n8n_main_cpu_limit, memory = var.n8n_main_memory_limit }
      }
      worker = {
        requests = { cpu = var.n8n_worker_cpu_request, memory = var.n8n_worker_memory_request }
        limits   = { cpu = var.n8n_worker_cpu_limit, memory = var.n8n_worker_memory_limit }
      }
      webhookProcessor = {
        requests = { cpu = var.n8n_webhook_cpu_request, memory = var.n8n_webhook_memory_request }
        limits   = { cpu = var.n8n_webhook_cpu_limit, memory = var.n8n_webhook_memory_limit }
      }
    }

    executions = {
      timeout     = var.n8n_execution_timeout
      timeoutMax  = var.n8n_execution_timeout_max
      concurrency = { productionLimit = var.n8n_execution_concurrency_limit }
      data = {
        saveOnError          = var.n8n_executions_data_save_on_error
        saveOnSuccess        = var.n8n_executions_data_save_on_success
        saveOnProgress       = var.n8n_executions_data_save_on_progress
        saveManualExecutions = var.n8n_executions_data_save_manual_executions
      }
      pruning = {
        enabled            = true
        maxAge             = var.n8n_pruning_max_age
        maxCount           = var.n8n_pruning_max_count
        hardDeleteBuffer   = 1
        hardDeleteInterval = 15
        softDeleteInterval = 60
      }
    }

    config = {
      timezone = var.n8n_timezone
      extraEnv = concat(
        # Direct connections to RDS/Aurora use SSL with the AWS CA (not trusted by Node.js — safe
        # to skip cert verification within the VPC). Set db_postgresdb_ssl_enabled = false when
        # n8n's DB host is an in-cluster pooler (e.g. PgBouncer) that handles SSL on its upstream leg.
        var.db_postgresdb_ssl_enabled ? [
          { name = "DB_POSTGRESDB_SSL_ENABLED", value = "true" },
          { name = "DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED", value = "false" },
          ] : [
          { name = "DB_POSTGRESDB_SSL_ENABLED", value = "false" },
        ],
        [
          { name = "N8N_LOG_LEVEL", value = var.n8n_log_level },
          # N8N_LOG_OUTPUT controls *where* logs go (console / file), not their
          # format. Setting it to anything other than "console" / "file" / a
          # comma-separated combination leaves Winston without a transport, at
          # which point every log line is replaced with a Winston warning and
          # the actual logs are silently dropped. See variable description.
          { name = "N8N_LOG_OUTPUT", value = var.n8n_log_output },
          { name = "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS", value = "true" },
          # Override the internally computed http://host:5678 URL so webhooks show the correct HTTPS address.
          { name = "WEBHOOK_URL", value = coalesce(var.n8n_webhook_url, "https://${local.n8n_domain}") },
          # The editor's own base URL, and what n8n builds absolute non-webhook
          # URLs from: UrlService.getInstanceBaseUrl() prefers
          # N8N_EDITOR_BASE_URL and falls back to WEBHOOK_URL when it is unset.
          # Above all it forms the OAuth2 credential redirect URI,
          # <editor base>/rest/oauth2-credential/callback.
          #
          # Unset until now, which is harmless only while the two URLs agree.
          # On a split hostname (n8n_webhook_url naming a second host, as
          # examples/split-ingress does) the fallback labels the editor with
          # the webhook hostname, and that callback 404s twice over: a split
          # ingress routes only the webhook prefixes there, and the webhook
          # processors serve no /rest routes even when reached. Webhook
          # delivery keeps working throughout, which points the search at the
          # wrong half. The chart cannot supply it either: it derives this from
          # its own ingress host or from webhook.url, and this module sets
          # neither (docs/helm-chart-coverage.md), so nothing emits it at all.
          #
          # n8n_domain rather than the webhook URL because n8n_domain is
          # canonical: it is the name the editor is served on, what N8N_HOST
          # already carries, and what n8n_additional_domains is defined
          # against. Deployments where the two agree render the value n8n
          # already resolves to today, so only a split hostname sees a change.
          { name = "N8N_EDITOR_BASE_URL", value = "https://${local.n8n_domain}" },
          { name = "N8N_RUNNERS_TASK_REQUEST_TIMEOUT", value = tostring(var.n8n_task_runner_request_timeout) },
          # Keeps ElastiCache from dropping idle Redis subscriber connections under sustained load.
          # Without this, Bull detects dropped connections, emits queue errors, and pods crash.
          { name = "QUEUE_BULL_REDIS_KEEP_ALIVE", value = "true" },
        ],
        # Scopes n8n's scaling-mode pub/sub command channel ("<prefix>:n8n.commands")
        # to this deployment. The chart has no dedicated field for this env var
        # (unlike QUEUE_BULL_PREFIX, wired via redis.prefix above), so it's a
        # literal extraEnv entry here. Omitted entirely on the null path,
        # leaving n8n's own "n8n" default exactly as before. See redis_key_prefix.
        var.redis_key_prefix != null ? [
          { name = "N8N_REDIS_KEY_PREFIX", value = var.redis_key_prefix },
        ] : [],
        # Database connection acquisition and health-check ping settings. The
        # chart has no values path for these and `DB_` is a module-managed
        # prefix, so n8n_extra_env cannot reach them. Each is omitted on the
        # null path, leaving n8n's own defaults.
        #
        # DB_POSTGRESDB_CONNECTION_TIMEOUT becomes pg-pool's
        # connectionTimeoutMillis, which bounds both connection establishment
        # and waiting for the shared pool to free a slot. The database monitor
        # also calls pool.connect(), so its acquisition is subject to this
        # timeout and to the separate DB_PING_TIMEOUT_MS race. The effective
        # health-check acquisition deadline is whichever timeout fires first.
        #
        # This interaction matters under load. A pool saturated by ordinary
        # database operations can make the ping time out while the database is
        # healthy. One timed-out ping marks the pod disconnected, so its global
        # middleware returns 503. Repeated failures make n8n destroy and
        # recreate the pool, suspending in-flight acquisition on that pod.
        var.db_postgresdb_connection_timeout_ms != null ? [
          { name = "DB_POSTGRESDB_CONNECTION_TIMEOUT", value = tostring(var.db_postgresdb_connection_timeout_ms) },
        ] : [],
        var.db_ping_timeout_ms != null ? [
          { name = "DB_PING_TIMEOUT_MS", value = tostring(var.db_ping_timeout_ms) },
        ] : [],
        var.db_ping_interval_seconds != null ? [
          { name = "DB_PING_INTERVAL_SECONDS", value = tostring(var.db_ping_interval_seconds) },
        ] : [],
        var.db_ping_max_failures_before_recovery != null ? [
          { name = "DB_PING_MAX_FAILURES_BEFORE_RECOVERY", value = tostring(var.db_ping_max_failures_before_recovery) },
        ] : [],
        [
          { name = "DB_POSTGRESDB_POOL_SIZE", value = tostring(var.db_postgresdb_pool_size) },
          # n8n's upstream default (true) makes the leader main detach its floating
          # license entitlement on shutdown, zeroing the shared cert in the database.
          # In multi-main (the module default) a fresh main pod then starts as a
          # follower, never renews on init, reads the zeroed cert, and crash-loops on
          # the license gate (n8n-io/terraform-aws-n8n#49). All mains share the same
          # device fingerprint, so keeping this false reuses a single floating seat
          # across restarts instead of releasing and re-acquiring it. Always emitted
          # (unlike opt-in toggles) because the module default deliberately overrides
          # n8n's own default.
          { name = "N8N_LICENSE_DETACH_FLOATING_ON_SHUTDOWN", value = tostring(var.n8n_license_detach_floating_on_shutdown) },
        ],
        # n8n exposes Prometheus metrics on /metrics over its HTTP port (5678) when
        # N8N_METRICS is set. The pinned chart version exposes no metrics /
        # serviceMonitor block (verified via `helm show values` against
        # var.n8n_chart_version), so the toggle is env-var-only — omit the var
        # entirely when disabled so n8n's own defaults apply (prefix, default
        # process metrics, etc). Scrape config is the caller's job.
        var.n8n_metrics_enabled ? [
          { name = "N8N_METRICS", value = "true" },
        ] : [],
        # Community-package handling. Both map straight to the n8n env vars and
        # default to n8n's own behavior (env var omitted), so only an explicit
        # opt-in changes anything. N8N_REINSTALL_MISSING_PACKAGES is what makes
        # workers reinstall UI-installed community nodes after they are
        # rescheduled onto a fresh, empty filesystem — without it those nodes
        # load on main but fail on workers in queue mode.
        var.n8n_reinstall_missing_packages ? [
          { name = "N8N_REINSTALL_MISSING_PACKAGES", value = "true" },
        ] : [],
        var.n8n_community_packages_prevent_loading ? [
          { name = "N8N_COMMUNITY_PACKAGES_PREVENT_LOADING", value = "true" },
        ] : [],
        # Private npm mirror for community package installs. Omitted unless set,
        # so n8n's own default (https://registry.npmjs.org) applies. The
        # companion N8N_COMMUNITY_PACKAGES_AUTH_TOKEN is deliberately not
        # managed here: it is a credential, and config.extraEnv renders into
        # the Helm release and Terraform state in plaintext.
        var.n8n_community_packages_registry == null ? [] : [
          { name = "N8N_COMMUNITY_PACKAGES_REGISTRY", value = var.n8n_community_packages_registry },
        ],
        # Directory n8n scans for custom nodes at startup, which is how nodes
        # baked into a custom image are picked up: since n8n 1.0 the loader
        # ignores the image's global node_modules entirely. Applied to every pod
        # type, because a node type that resolves on main and not on workers
        # fails at execution time instead of at edit time.
        var.n8n_custom_extensions_path == null ? [] : [
          { name = "N8N_CUSTOM_EXTENSIONS", value = var.n8n_custom_extensions_path },
        ],
        # n8n defaults scheduled to change. n8n warns on every pod start that
        # these four will move in a future version and asks operators to set
        # them explicitly to keep today's behavior.
        #
        # Only the task timeout is emitted unconditionally, because only its
        # change is a pure functional regression: n8n has announced the default
        # drops from 300 to 60, which would abort every Code node task running
        # longer than a minute after an upgrade that changed nothing else.
        # Pinning it means an upgrade cannot move it silently. See
        # var.n8n_task_runner_timeout for why the other three are not pinned.
        [
          { name = "N8N_RUNNERS_TASK_TIMEOUT", value = tostring(var.n8n_task_runner_timeout) },
        ],
        var.n8n_unverified_packages_enabled == null ? [] : [
          { name = "N8N_UNVERIFIED_PACKAGES_ENABLED", value = tostring(var.n8n_unverified_packages_enabled) },
        ],
        var.n8n_compression_max_decompressed_size_bytes == null ? [] : [
          { name = "N8N_COMPRESSION_NODE_MAX_DECOMPRESSED_SIZE_BYTES", value = tostring(var.n8n_compression_max_decompressed_size_bytes) },
        ],
        var.n8n_compression_max_zip_entries == null ? [] : [
          { name = "N8N_COMPRESSION_NODE_MAX_ZIP_ENTRIES", value = tostring(var.n8n_compression_max_zip_entries) },
        ],

        # Execution-data offload to S3 (n8n >= 2.27, Enterprise). The chart has
        # no value for this at var.n8n_chart_version (its s3.storage block only
        # covers *binary* data), so it goes through config.extraEnv, which the
        # chart applies to every n8n container. That matters: the n8n docs require
        # N8N_EXECUTION_DATA_STORAGE_MODE on all instances in queue mode,
        # including workers and webhook processors, not just the mains.
        #
        # The connection itself is already in place: this reuses the
        # N8N_EXTERNAL_STORAGE_S3_* values the chart renders from the s3 block
        # above and the Pod Identity role from s3.tf, so nothing else is needed.
        # Emitted only for "s3"; "database" is n8n's own default, so the env var
        # is omitted entirely there.
        var.n8n_execution_data_storage_mode == "s3" ? [
          { name = "N8N_EXECUTION_DATA_STORAGE_MODE", value = "s3" },
        ] : [],

        # n8n's own module system. local.n8n_disabled_modules collapses to []
        # unless n8n_external_secrets_enabled = false, so the default apply
        # emits no N8N_DISABLED_MODULES at all.
        length(local.n8n_disabled_modules) > 0 ? [
          { name = "N8N_DISABLED_MODULES", value = join(",", local.n8n_disabled_modules) },
        ] : [],
        var.n8n_external_secrets_update_interval == null ? [] : [
          { name = "N8N_EXTERNAL_SECRETS_UPDATE_INTERVAL", value = tostring(var.n8n_external_secrets_update_interval) },
        ],

        # n8n feature toggles: templates and personalization. Only set the env
        # var when disabled (false) to override n8n's defaults. When enabled
        # (true), the env var is omitted so n8n's defaults apply.
        !var.n8n_templates_enabled ? [
          { name = "N8N_TEMPLATES_ENABLED", value = "false" },
        ] : [],
        !var.n8n_personalization_enabled ? [
          { name = "N8N_PERSONALIZATION_ENABLED", value = "false" },
        ] : [],

        # n8n OpenTelemetry tracing. config.extraEnv applies to every n8n
        # container in the multi-main topology (main, worker, webhook
        # processor), which matches the OTEL docs' queue-mode requirement
        # (https://docs.n8n.io/hosting/logging-monitoring/opentelemetry/).
        #
        # Master switch first; each individual tuning var is null-default and
        # only emitted when explicitly set, so n8n's own defaults apply
        # otherwise. When n8n_otel_enabled = false the whole block collapses
        # to [] and no N8N_OTEL_* env vars are set on the pods.
        var.n8n_otel_enabled ? concat(
          [{ name = "N8N_OTEL_ENABLED", value = "true" }],
          var.n8n_otel_exporter_otlp_endpoint == null ? [] : [
            { name = "N8N_OTEL_EXPORTER_OTLP_ENDPOINT", value = var.n8n_otel_exporter_otlp_endpoint },
          ],
          var.n8n_otel_exporter_otlp_headers == null ? [] : [
            { name = "N8N_OTEL_EXPORTER_OTLP_HEADERS", value = var.n8n_otel_exporter_otlp_headers },
          ],
          var.n8n_otel_exporter_service_name == null ? [] : [
            { name = "N8N_OTEL_EXPORTER_SERVICE_NAME", value = var.n8n_otel_exporter_service_name },
          ],
          var.n8n_otel_traces_sample_rate == null ? [] : [
            { name = "N8N_OTEL_TRACES_SAMPLE_RATE", value = tostring(var.n8n_otel_traces_sample_rate) },
          ],
          var.n8n_otel_traces_include_node_spans == null ? [] : [
            { name = "N8N_OTEL_TRACES_INCLUDE_NODE_SPANS", value = tostring(var.n8n_otel_traces_include_node_spans) },
          ],
          var.n8n_otel_traces_inject_outbound == null ? [] : [
            { name = "N8N_OTEL_TRACES_INJECT_OUTBOUND", value = tostring(var.n8n_otel_traces_inject_outbound) },
          ],
          var.n8n_otel_traces_production_only == null ? [] : [
            { name = "N8N_OTEL_TRACES_PRODUCTION_ONLY", value = tostring(var.n8n_otel_traces_production_only) },
          ],
        ) : [],

        # n8n Enterprise log streaming, managed declaratively via env vars
        # (settings-env-vars activation pattern, n8n >= 2.19.0). When the
        # master switch is on, n8n reapplies the destinations on every startup
        # and locks the Log Streaming UI read-only. The destinations list is
        # JSON-encoded — n8n expects a JSON array in
        # N8N_LOG_STREAMING_DESTINATIONS. When the master switch is off the
        # block collapses to [] and destinations stay UI-managed.
        var.n8n_log_streaming_managed_by_env ? concat(
          [{ name = "N8N_LOG_STREAMING_MANAGED_BY_ENV", value = "true" }],
          length(var.n8n_log_streaming_destinations) > 0 ? [
            { name = "N8N_LOG_STREAMING_DESTINATIONS", value = jsonencode(var.n8n_log_streaming_destinations) },
          ] : [],
        ) : [],

        # Caller-supplied escape hatch, appended last. Kubernetes resolves
        # duplicate env names last-wins, so this would override anything above
        # it; var.n8n_extra_env is validated against local.n8n_managed_env_names
        # and local.n8n_managed_env_prefixes (variables.tf) so it cannot shadow a
        # module- or chart-managed connection/identity/storage/license var.
        var.n8n_extra_env
      )
    }

    # ── Graceful shutdown ─────────────────────────────────────────────────────
    # preStop sleep drains the pod from load balancer backends before SIGTERM.
    # terminationGracePeriodSeconds gives in-flight executions time to complete.
    lifecycle = {
      main = {
        terminationGracePeriodSeconds = var.n8n_termination_grace_period
        preStop = {
          enabled = true
          command = ["/bin/sh", "-c", "sleep ${var.n8n_prestop_sleep}"]
        }
      }
      worker = {
        terminationGracePeriodSeconds = var.n8n_termination_grace_period
        preStop = {
          enabled = true
          command = ["/bin/sh", "-c", "sleep ${var.n8n_prestop_sleep}"]
        }
      }
      webhookProcessor = {
        terminationGracePeriodSeconds = var.n8n_termination_grace_period
        preStop = {
          enabled = true
          command = ["/bin/sh", "-c", "sleep ${var.n8n_prestop_sleep}"]
        }
      }
    }

    # ── Task runners ─────────────────────────────────────────────────────────
    # When enabled, a sidecar container (n8nio/runners) is added to both main and
    # worker pods to execute JavaScript and Python code in isolation from the n8n
    # process. The n8n container runs a task broker on port 5679; each sidecar
    # connects to it over localhost using the auto-generated auth token.
    #
    # The sidecar's image tag is left to the chart, which defaults it to the n8n
    # application image's tag (`default .Values.image.tag
    # .Values.taskRunners.image.tag` in deployment-main.yaml and
    # deployment-worker.yaml). That is correct for a published n8n tag but wrong
    # for a custom image tagged something like "2.27.4-mypackages", since no such
    # `n8nio/runners` tag exists, hence the n8n_task_runner_image_tag override,
    # merged in only when set so the chart's inheritance stays the default.
    taskRunners = merge({
      enabled = var.n8n_task_runners_enabled
      authToken = {
        value = random_password.task_runner_token.result
      }
      broker = {
        listenAddress = "0.0.0.0"
        port          = 5679
      }
      launcher = {
        logLevel            = "info"
        autoShutdownTimeout = var.n8n_task_runner_auto_shutdown_timeout
      }
      nativePythonRunner = var.n8n_task_runner_python_enabled
      resources = {
        requests = { cpu = var.n8n_task_runner_cpu_request, memory = var.n8n_task_runner_memory_request }
        limits   = { cpu = var.n8n_task_runner_cpu_limit, memory = var.n8n_task_runner_memory_limit }
      }
      },
      var.n8n_task_runner_image_tag == null ? {} : { image = { tag = var.n8n_task_runner_image_tag } },

      # Custom launcher config, mounted over the runner image's baked-in
      # /etc/n8n-task-runners.json from a ConfigMap the caller creates.
      #
      # This is the only route to the runner allow-lists. The image ships the
      # native Python runner with N8N_RUNNERS_STDLIB_ALLOW set to "", which
      # refuses every stdlib import, and neither allow-list can be set by an env
      # var: the names are absent from each runner's `allowed-env`, so the
      # launcher never forwards them to the runner process, and the file's own
      # `env-overrides` is applied regardless and would win anyway.
      #
      # Merged in only when set, so the chart's default (customConfig disabled,
      # image config used) stays the default.
      var.n8n_task_runner_custom_config == null ? {} : {
        customConfig = {
          enabled       = true
          configMapName = var.n8n_task_runner_custom_config.config_map_name
          configMapKey  = var.n8n_task_runner_custom_config.config_map_key
        }
      },
    )

    # ── Pod Disruption Budget ─────────────────────────────────────────────────
    # Ensures at least one main pod stays running during node drains or rollouts.
    pdb = {
      enabled      = true
      minAvailable = 1
    }

    # ── Extra volumes ─────────────────────────────────────────────────────────
    # Rendered onto main, worker and webhook-processor alike. Both default to an
    # empty list, which is also the chart's default, so an unset caller sees no
    # change. The snake_case-to-camelCase translation lives in locals.tf: the
    # whole values string is unknown at plan time (it carries the S3 role ARN
    # and the database endpoint), so anything asserted about it has to be
    # reachable without reading it back off the resource.
    extraVolumes      = local.n8n_extra_volumes
    extraVolumeMounts = local.n8n_extra_volume_mounts
    },
    # Override the app image only where the caller asks for it; otherwise the
    # chart defaults apply untouched (docker.n8n.io/n8nio/n8n:stable). Repository
    # and tag are merged key by key rather than as a whole `image` map so setting
    # one does not blank the other: yamlencode would emit `repository: null`,
    # which the chart renders into an unpullable `null:2.27.4` reference.
    var.n8n_image_repository == null && var.n8n_image_tag == null ? {} : {
      image = merge(
        var.n8n_image_repository == null ? {} : { repository = var.n8n_image_repository },
        var.n8n_image_tag == null ? {} : { tag = var.n8n_image_tag },
      )
    },

    # ── Roll the pods when the AUTH token changes ─────────────────────────────
    # kubernetes_secret.n8n_redis is referenced by NAME from redis.passwordSecret
    # above, so its contents are not part of the rendered Helm values. Rotating
    # the token therefore updates the Secret and the replication group but
    # produces no Helm diff, and nothing restarts: env vars sourced from a
    # secretKeyRef are resolved once at pod start, so every running pod keeps
    # the old token indefinitely.
    #
    # auth_token_update_strategy = "ROTATE" (redis.tf) is what stops that being
    # an immediate outage: AWS keeps the previous token valid alongside the new
    # one. It is not a fix, only a grace period. The next rotation invalidates
    # the token those pods are still holding, and the queue stops.
    #
    # The chart computes its own checksum/config and checksum/secret pod
    # annotations, but checksum/secret hashes templates/secrets.yaml, which
    # renders secretRefs.env only. A Secret created outside the chart, as this
    # one is, can never move that hash. podAnnotations is the seam that works:
    # the chart merges it into all three pod templates (main, worker, webhook
    # processor), so a changed value rolls exactly the pods that hold the token.
    #
    # CAVEAT: podAnnotations is accepted by the templates but is NOT documented
    # in the chart's values.yaml, so it is an implicit interface that could be
    # renamed without a breaking-change note. Verified present at the pinned
    # n8n_chart_version (1.10.0) and still present at 1.11.0. If a chart bump
    # ever silently drops it, rotation goes back to being manual rather than
    # breaking anything, and the test in defaults.tftest.hcl pins the shape.
    #
    # The hash, never the token: annotations are readable by anyone who can get
    # a pod, and sha256 is enough to change when the token changes.
    #
    # Merged conditionally rather than emitted as an empty map, for the same
    # reason redis.timeout is: a default deployment must render byte-identical
    # values to what it renders today, or every existing release sees a Helm
    # diff on upgrade.
    #
    # Also gated on redis_auth_token_secret_ref being null: with a
    # caller-managed Secret the module never reads the token value, so it has
    # nothing to hash, and local.redis_pod_annotations resolves to {} on that
    # path for the same reason.
    (local.redis_auth_active && var.redis_auth_token_secret_ref == null) ? { podAnnotations = local.redis_pod_annotations } : {},

    # Pod DNS. Omitted entirely unless n8n_dns_config is set, so this is a no-op
    # by default. See that variable for why it exists (ndots:5 search-path
    # amplification measured at 80% wasted DNS queries under load).
    #
    # local.n8n_dns_config, not var.n8n_dns_config: the variable's optional()
    # attributes materialise as nulls when unset, and yamlencode would emit
    # `nameservers: null` into the chart's `{{- toYaml . }}`, which the API
    # server rejects as an invalid pod spec. The local strips unset keys.
    local.n8n_dns_config == null ? {} : { dnsConfig = local.n8n_dns_config },
  ))]

  depends_on = [
    # See the comment on kubernetes_secret.n8n above: local.namespace_name
    # carries no dependency on the node group when create_namespace = false.
    aws_eks_node_group.n8n,
    # Depending on the whole controllers module rather than helm_release.lbc /
    # helm_release.keda individually: those two resources now live in
    # module.controllers, and a module-level dependency is a strict superset
    # of the two-resource dependency this replaced (it also waits on
    # metrics-server, cluster-autoscaler and the EBS CSI driver, all of which
    # are no-ops for this ordering but harmless to wait on).
    module.controllers,
    aws_db_instance.n8n, # no-op (empty list) when create_database = false
    # Exactly one of these is non-empty when create_elasticache = true, and both
    # are empty when it is false. Listing both keeps the edge regardless of
    # which Redis topology redis_high_availability_enabled selected.
    aws_elasticache_cluster.n8n,
    aws_elasticache_replication_group.n8n,
    aws_iam_role_policy_attachment.s3,
    aws_eks_pod_identity_association.s3,
    kubernetes_service_account_v1.n8n, # empty list unless the module owns it
  ]
}

# ── Ingress ───────────────────────────────────────────────────────────────────
# A single ALB fronting both Services: the webhook path prefixes go to the
# webhook processors, everything else to the mains. Annotations come from
# local.ingress_annotations (module defaults overlaid with var.ingress_annotations)
# and the routed prefixes from local.n8n_webhook_path_prefixes. See locals.tf
# for why each is what it is.
#
# Skipped when create_ingress = false. The caller then owns routing entirely
# (e.g. a public internet-facing ALB for the webhook prefixes plus a separate
# internal, VPN-only ALB for the admin UI). The module still creates the
# Services the caller's Ingresses point at: n8n-main and n8n-webhook-processor,
# both :5678. Those coordinates, and the webhook prefix list, are exposed as
# outputs so a caller-built Ingress cannot drift from what n8n actually serves.

resource "kubernetes_ingress_v1" "n8n" {
  count = var.create_ingress ? 1 : 0

  metadata {
    name        = "n8n-ingress"
    namespace   = local.namespace_name
    annotations = local.ingress_annotations
  }

  spec {
    ingress_class_name = "alb"

    # One rule per hostname the certificate covers. With no additional domains
    # this renders exactly the single rule it always did, so existing
    # deployments see no diff.
    dynamic "rule" {
      for_each = local.acm_domain_names

      content {
        host = rule.value
        http {
          # Webhook, form, waiting and MCP traffic must reach the dedicated
          # webhook processors, because the mains serve none of it. Declared before the
          # catch-all so the more specific prefixes win.
          dynamic "path" {
            for_each = local.n8n_webhook_path_prefixes

            content {
              path      = path.value
              path_type = "Prefix"
              backend {
                service {
                  name = local.n8n_webhook_service_name
                  port { number = local.n8n_service_port }
                }
              }
            }
          }

          # Editor UI and REST API.
          path {
            path      = "/"
            path_type = "Prefix"
            backend {
              service {
                name = local.n8n_service_name
                port { number = local.n8n_service_port }
              }
            }
          }
        }
      }
    }
  }

  wait_for_load_balancer = true

  # delete is generous because tearing an Ingress down is a two-step dance with
  # the AWS Load Balancer Controller and ELBv2, not a single API call. LBC
  # deletes the ALB, then its target groups, but ELBv2 keeps reporting a target
  # group as "in use by a listener or a rule" for several minutes after the load
  # balancer is already gone. LBC retries and holds the ingress.k8s.aws/resources
  # finalizer until it succeeds. Observed taking ~9 minutes on a live teardown,
  # so a 5m timeout fails the destroy and leaves the Ingress stuck mid-deletion,
  # needing manual recovery. See docs/destroy-cleanup.md.
  timeouts {
    create = "10m"
    delete = "20m"
  }

  depends_on = [
    helm_release.n8n,
    # aws_iam_role.lbc / aws_iam_role_policy_attachment.lbc now live in
    # module.controllers; depending on the whole module is a strict superset.
    module.controllers,
    time_sleep.wait_for_alb_cleanup,
  ]
}

# ── Destroy-time pause ────────────────────────────────────────────────────────
# After the Ingress is deleted, the LBC begins deprovisioning the ALB. The ALB
# deletion is asynchronous — ENIs and security groups may linger for 30-60s.
# This pause gives AWS time to fully release those resources before Terraform
# moves on to deleting the namespace, node group, and cluster.
#
# Dependency chain (create order, reversed for destroy):
#   namespace → time_sleep → ingress
# Destroy order (reversed):
#   1. kubernetes_ingress_v1.n8n        ← Ingress deleted, LBC starts ALB teardown
#   2. time_sleep.wait_for_alb_cleanup  ← pauses 60s for ENI/SG release
#   3. kubernetes_namespace.n8n         ← namespace deleted (resources fully gone)

resource "time_sleep" "wait_for_alb_cleanup" {
  destroy_duration = "60s"

  depends_on = [kubernetes_namespace.n8n]
}

# ── Ingress scheme conflict check ──────────────────────────────────────────
# ingress_annotations is merged over the module defaults, so a scheme set there
# silently wins over var.ingress_scheme. Getting that backwards is the one
# override with a security consequence: an admin UI expected to be internal
# ends up internet-facing, or vice versa. Warn rather than let it pass
# unremarked. A `check` block emits a warning without failing plan or apply:
# specifying the annotation directly stays legitimate as long as it is
# deliberate, and callers who set only ingress_annotations (never touching
# ingress_scheme) are not forced to migrate.
#
# Gated on var.create_ingress for the same reason as the ALB source-restriction
# checks below: the override it describes happens on the Ingress this module
# creates, so with create_ingress = false there is no module-managed ALB to take
# the annotation value and ingress_tuning_requires_module_managed_ingress
# already covers that mode accurately.

check "ingress_scheme_not_overridden_by_annotations" {
  assert {
    condition = var.create_ingress ? !contains(
      keys(var.ingress_annotations), "alb.ingress.kubernetes.io/scheme"
    ) : true
    error_message = join("", [
      "ingress_annotations sets alb.ingress.kubernetes.io/scheme, which overrides var.ingress_scheme ",
      "(currently \"${var.ingress_scheme}\"). The ALB will use the annotation value. ",
      "Set the scheme through var.ingress_scheme instead: it is validated and drives the module's own DNS wiring.",
    ])
  }
}

# ── ALB SSL policy conflict check ──────────────────────────────────────────
# Same hazard as the scheme check above: ingress_annotations is merged over
# the module defaults, so an ssl-policy set there silently wins over
# var.alb_ssl_policy. Warn rather than let a caller believe the validated
# variable is what is actually in effect.

check "alb_ssl_policy_not_overridden_by_annotations" {
  assert {
    condition = !contains(keys(var.ingress_annotations), "alb.ingress.kubernetes.io/ssl-policy")
    error_message = join("", [
      "ingress_annotations sets alb.ingress.kubernetes.io/ssl-policy, which overrides var.alb_ssl_policy ",
      "(currently \"${var.alb_ssl_policy}\"). The ALB will use the annotation value. ",
      "Set the policy through var.alb_ssl_policy instead: it is validated against the ELBSecurityPolicy- prefix.",
    ])
  }
}

# ── Ingress tuning without a module-managed Ingress ────────────────────────
# ingress_scheme, alb_ssl_policy, ingress_annotations, and the two ALB
# source-restriction inputs only reach an Ingress this module creates. With
# create_ingress = false they are inert, and silence would leave a caller
# believing an internal scheme, a pinned TLS policy, a WAF association, or a
# source restriction had taken effect when their own Ingress carries none of
# it. The source-restriction case is the worst of the five: the caller
# believes the ALB is reachable only from their VPN range.

check "ingress_tuning_requires_module_managed_ingress" {
  assert {
    condition = var.create_ingress ? true : (
      var.ingress_scheme == "internet-facing" &&
      var.alb_ssl_policy == local.alb_ssl_policy_default &&
      length(var.ingress_annotations) == 0 &&
      length(var.alb_inbound_cidrs) == 0 &&
      length(var.alb_inbound_prefix_list_ids) == 0
    )
    error_message = join("", [
      "ingress_scheme, alb_ssl_policy, ingress_annotations, alb_inbound_cidrs, or alb_inbound_prefix_list_ids ",
      "is set while create_ingress = false, so none of it is applied to anything. With create_ingress = false ",
      "you own the Ingress resources; put the scheme, TLS policy, annotations, and source restrictions on ",
      "your own Ingress instead.",
    ])
  }
}

# ── ALB source restriction conflict checks ─────────────────────────────────
# Two ways to ask for a restricted ALB and get an open one instead. Both are
# warnings rather than plan failures: each combination stays legitimate when it
# is deliberate, and neither is reachable by a caller who simply upgrades.
#
# Both are gated on var.create_ingress, matching
# ingress_annotations_preserve_session_stickiness below. Every conflict they
# describe is a conflict on the Ingress this module creates, so with
# create_ingress = false there is no module-managed ALB for an annotation to win
# on, and the warning would describe a load balancer that does not exist. That
# mode already has its own warning in
# ingress_tuning_requires_module_managed_ingress above, which says the accurate
# thing: none of these inputs is applied to anything.

# ingress_annotations is merged last (see locals.tf), so an inbound-cidrs or
# security-group-prefix-lists key there beats the dedicated input. That
# precedence is deliberate: the key was the documented way to restrict the ALB
# before these inputs existed, so it keeps working. The footgun is the
# half-finished migration, where the new input is added and the old annotation
# is left behind, and the ALB stays on the stale range.

check "alb_source_restrictions_not_overridden_by_annotations" {
  assert {
    condition = var.create_ingress ? (
      length(var.alb_inbound_cidrs) > 0 ? !contains(
        keys(var.ingress_annotations), "alb.ingress.kubernetes.io/inbound-cidrs"
      ) : true
    ) : true
    error_message = join("", [
      "alb_inbound_cidrs is set, but ingress_annotations also sets alb.ingress.kubernetes.io/inbound-cidrs, ",
      "which is merged last and wins. The ALB will use the annotation value and ignore alb_inbound_cidrs ",
      "entirely. Remove the annotation and keep the values in alb_inbound_cidrs, which is validated.",
    ])
  }

  assert {
    condition = var.create_ingress ? (
      length(var.alb_inbound_prefix_list_ids) > 0 ? !contains(
        keys(var.ingress_annotations), "alb.ingress.kubernetes.io/security-group-prefix-lists"
      ) : true
    ) : true
    error_message = join("", [
      "alb_inbound_prefix_list_ids is set, but ingress_annotations also sets ",
      "alb.ingress.kubernetes.io/security-group-prefix-lists, which is merged last and wins. The ALB will ",
      "use the annotation value and ignore alb_inbound_prefix_list_ids entirely. Remove the annotation and ",
      "keep the values in alb_inbound_prefix_list_ids, which is validated.",
    ])
  }
}

# A fourth path exists in the controller but cannot reach this Ingress, so it
# gets neither a check block nor a warning. An IngressClassParams that sets
# spec.inboundCIDRs or spec.prefixListsIDs does replace the annotation outright,
# per field, rather than merging with it. Reaching it takes two things that are
# both false here: the IngressClass has to reference the params object through
# spec.parameters, which the LBC chart does not set up even though it creates
# both objects, and the Ingress has to be classified through
# spec.ingressClassName. This Ingress carries the legacy
# kubernetes.io/ingress.class annotation as well (locals.tf), and the controller
# matches that first and returns before it ever loads the IngressClass, so the
# params object is never consulted for this Ingress.
#
# Verified live against LBC v3.5.0: with the params bound and populated, this
# module's alb_inbound_cidrs still won, and the override only took effect once
# the legacy annotation was removed by hand. Do not add a check block for it.
# Beyond the module having no data source for a cluster-scoped object it does not
# create, and a plan-time cluster read coupling every plan to a live API call,
# the condition would warn about something that cannot happen here. Caller-owned
# Ingresses using only spec.ingressClassName, examples/split-ingress included,
# are exposed; that is documented in docs/troubleshooting.md.
#
# The AWS Load Balancer Controller ignores both inbound-cidrs and
# security-group-prefix-lists when alb.ingress.kubernetes.io/security-groups is
# specified, because the caller then owns the ALB's security group and the
# controller stops managing its rules. Nothing in the plan reveals this: the
# annotations render, the apply succeeds, and the restriction never exists. An
# operator who believes the editor UI is VPN-only is the one who most needs to
# hear about it, so warn even though the combination is not an error.

check "alb_source_restrictions_require_controller_managed_security_group" {
  assert {
    # concat rather than `||`: check conditions in this module avoid chained
    # boolean operators, which do not short-circuit on Terraform 1.9.
    condition = var.create_ingress ? (
      length(concat(var.alb_inbound_cidrs, var.alb_inbound_prefix_list_ids)) > 0 ? !contains(
        keys(var.ingress_annotations), "alb.ingress.kubernetes.io/security-groups"
      ) : true
    ) : true
    error_message = join("", [
      "alb_inbound_cidrs or alb_inbound_prefix_list_ids is set alongside ",
      "alb.ingress.kubernetes.io/security-groups in ingress_annotations. The AWS Load Balancer Controller ",
      "ignores both source restrictions when you supply your own security groups, so the ALB will accept ",
      "traffic from anywhere those groups allow. Put the source restriction in the security group rules ",
      "themselves, or drop the security-groups annotation and let the controller manage the group.",
    ])
  }
}

# ── Session stickiness override check ──────────────────────────────────────
# target-group-attributes is the one module default whose replacement has a
# non-obvious cost. It carries the lb_cookie stickiness that pins a browser to
# a single main pod; drop it and the ALB round-robins, which breaks the editor's
# WebSocket connection in a way that looks like a flaky network rather than a
# config change. Warn only when the key is overridden *without* re-enabling
# stickiness, so a deliberate override that keeps it stays quiet.

check "ingress_annotations_preserve_session_stickiness" {
  assert {
    condition = var.create_ingress ? (
      contains(
        keys(var.ingress_annotations), "alb.ingress.kubernetes.io/target-group-attributes"
        ) ? strcontains(
        lookup(var.ingress_annotations, "alb.ingress.kubernetes.io/target-group-attributes", ""),
        "stickiness.enabled=true"
      ) : true
    ) : true
    error_message = join("", [
      "ingress_annotations overrides alb.ingress.kubernetes.io/target-group-attributes without ",
      "stickiness.enabled=true. The module default pins each browser to one main pod for 3 hours; ",
      "without it the ALB round-robins and editor WebSocket connections drop. Re-include ",
      "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=10800 unless you mean to disable it.",
    ])
  }
}

# ── OpenTelemetry diagnostic check ─────────────────────────────────────────
# Warns at plan time when any n8n_otel_* tuning variable is set while the
# master toggle n8n_otel_enabled is false. The OTEL wiring above collapses
# the entire N8N_OTEL_* env-var block to [] when the master is off — silent
# by design — so without this check a caller who sets, e.g.,
# n8n_otel_exporter_otlp_endpoint without also flipping n8n_otel_enabled
# would wonder why no traces are flowing.
#
# `check` block (Terraform 1.5+) emits a warning, not an error, so plan and
# apply still succeed. This is intentional: some callers will legitimately
# stage tuning config in tfvars before flipping the master switch.

check "otel_tuning_requires_master_switch" {
  assert {
    condition = var.n8n_otel_enabled || (
      var.n8n_otel_exporter_otlp_endpoint == null &&
      var.n8n_otel_exporter_otlp_headers == null &&
      var.n8n_otel_exporter_service_name == null &&
      var.n8n_otel_traces_sample_rate == null &&
      var.n8n_otel_traces_include_node_spans == null &&
      var.n8n_otel_traces_inject_outbound == null &&
      var.n8n_otel_traces_production_only == null
    )
    error_message = "One or more n8n_otel_* tuning variables are set, but n8n_otel_enabled is false — the tuning values will be ignored and no N8N_OTEL_* env vars will be set on the n8n pods. Set n8n_otel_enabled = true to apply them, or clear the tuning variables to silence this warning."
  }
}

# ── Execution-data S3 version check ────────────────────────────────────────
# N8N_EXECUTION_DATA_STORAGE_MODE only exists from n8n 2.27. On an older image
# the env var is simply ignored: pods come up healthy, the plan shows the mode
# applied, and execution data keeps going to PostgreSQL. The failure is entirely
# silent, which is what makes it worth a plan-time warning.
#
# Only a tag shaped like MAJOR.MINOR.<rest> is compared (this covers "2.27.4"
# and "2.27.4-alpine"); anything else, including null (the chart's floating
# `stable`) and pre-release or channel tags, is left alone rather than guessed
# at. Written as nested ternaries because Terraform 1.9 does not short-circuit
# `&&`/`||` (see AGENTS.md), so the numeric comparisons must sit on a branch
# that is only taken once the regex has confirmed they are numbers.

check "execution_data_s3_requires_n8n_2_27" {
  assert {
    condition = var.n8n_execution_data_storage_mode != "s3" ? true : (
      var.n8n_image_tag == null ? true : (
        can(regex("^[0-9]+\\.[0-9]+\\.", var.n8n_image_tag)) ? (
          tonumber(split(".", var.n8n_image_tag)[0]) > 2 ? true : (
            tonumber(split(".", var.n8n_image_tag)[0]) == 2 ? tonumber(split(".", var.n8n_image_tag)[1]) >= 27 : false
          )
        ) : true
      )
    )
    error_message = join("", [
      "n8n_execution_data_storage_mode = \"s3\" requires n8n >= 2.27, but n8n_image_tag is pinned to ",
      "\"${coalesce(var.n8n_image_tag, "null")}\". Older versions ignore N8N_EXECUTION_DATA_STORAGE_MODE ",
      "entirely: the pods start fine and execution data silently keeps going to PostgreSQL. Pin ",
      "n8n_image_tag to 2.27.0 or later, or set n8n_execution_data_storage_mode = \"database\".",
    ])
  }
}

# Same warning pattern for log streaming: destinations without the master
# switch are silently ignored by the wiring above (the env-var block collapses
# to []), so surface that at plan time as a non-blocking warning.

check "log_streaming_destinations_require_managed_by_env" {
  assert {
    condition = var.n8n_log_streaming_managed_by_env || (
      length(var.n8n_log_streaming_destinations) == 0
    )
    error_message = "n8n_log_streaming_destinations is set, but n8n_log_streaming_managed_by_env is false — the destinations will be ignored and no N8N_LOG_STREAMING_* env vars will be set on the n8n pods. Set n8n_log_streaming_managed_by_env = true to apply them, or clear the destinations to silence this warning."
  }
}

# ── Custom image guards ───────────────────────────────────────────────────────
# Six plan-time warnings for custom-image, extra-volume and pull-secret
# configurations that are accepted but almost certainly not what the caller
# meant. All are warnings rather than errors: each is legitimate in some
# deployment, and none can be decided with certainty from the inputs alone.
#
# Written as `guard ? body : true` per AGENTS.md, since Terraform 1.9 (the
# version floor) does not short-circuit && and ||.

check "custom_image_repository_needs_an_explicit_tag" {
  assert {
    condition     = var.n8n_image_repository != null ? var.n8n_image_tag != null : true
    error_message = "n8n_image_repository is set but n8n_image_tag is null, so the chart appends its own default and the release resolves to <repository>:stable. A custom registry rarely publishes a `stable` tag, and the pods then fail with ImagePullBackOff. Set n8n_image_tag to a tag that exists in this repository. Ignore this warning if the repository is a mirror that does publish `stable`."
  }
}

check "custom_image_tag_needs_a_task_runner_tag" {
  assert {
    condition = var.n8n_image_repository != null ? (
      var.n8n_task_runners_enabled ? (
        var.n8n_image_tag == null || var.n8n_task_runner_image_tag != null
      ) : true
    ) : true
    error_message = "A custom n8n image (n8n_image_repository + n8n_image_tag) is set with task runners enabled, but n8n_task_runner_image_tag is null. The chart tags the runner sidecar from the app image, so the sidecar resolves to n8nio/runners:<n8n_image_tag> and every main and worker pod fails with ImagePullBackOff unless that exact tag exists upstream, which fails the apply rather than completing with broken pods. Set n8n_task_runner_image_tag to the n8n version the custom image is built from. Ignore this warning if the custom image's tag is itself a published n8n version."
  }
}

check "custom_extensions_path_requires_a_source" {
  assert {
    # Two ways to put nodes at the path, so the warning has to rule out both:
    # a custom image that baked them in, or a volume mounted at or above it.
    condition = var.n8n_custom_extensions_path != null ? (
      var.n8n_image_repository != null ? true : anytrue([
        for mount in var.n8n_extra_volume_mounts :
        mount.mount_path == var.n8n_custom_extensions_path ||
        startswith(var.n8n_custom_extensions_path, "${mount.mount_path}/")
      ])
    ) : true
    error_message = "n8n_custom_extensions_path is set, but nothing in this configuration puts files there: n8n_image_repository is null, so the pods run the chart's stock image, and no n8n_extra_volume_mounts entry covers the path. n8n will scan an empty or missing directory and load no nodes, silently. Either point n8n_image_repository at an image with the compiled nodes baked in at this path, or mount a volume that carries them (see n8n_extra_volumes), or clear the path to silence this warning."
  }
}

check "extra_volumes_should_be_mounted" {
  assert {
    condition = alltrue([
      for volume in var.n8n_extra_volumes :
      contains([for mount in var.n8n_extra_volume_mounts : mount.name], volume.name)
    ])
    error_message = "An n8n_extra_volumes entry is never mounted, because no n8n_extra_volume_mounts entry names it. Kubernetes accepts an unmounted volume, so the pods will start and the files will simply not be there. Add a mount for it, or drop the volume. Ignore this warning only if the volume exists for something outside the n8n container."
  }
}

check "image_pull_secrets_need_a_custom_image" {
  assert {
    condition     = length(var.n8n_image_pull_secrets) > 0 ? var.n8n_image_repository != null : true
    error_message = "n8n_image_pull_secrets is set but n8n_image_repository is null, so every image the pods pull comes from a public registry: the chart's docker.n8n.io/n8nio/n8n and, with task runners on, n8nio/runners. Neither needs credentials, so the secrets are attached and never used. The cost is not zero: setting this input moves ownership of the ServiceAccount from the chart to the module. Clear it to hand the account back, or set n8n_image_repository to the private image these credentials are for."
  }
}

check "task_runner_image_tag_requires_task_runners" {
  assert {
    condition     = var.n8n_task_runner_image_tag != null ? var.n8n_task_runners_enabled : true
    error_message = "n8n_task_runner_image_tag is set, but n8n_task_runners_enabled is false, so no runner sidecar is deployed and the tag is ignored. Set n8n_task_runners_enabled = true to apply it, or clear the tag to silence this warning."
  }
}
